let suggestions = [
    "Channel" ,
    "CodingLab" ,
    "CodingNepal" ,
    "YouTube" ,
    "YouTuber" ,
    "YouTube Channel" ,
    "Blogger" ,
    "Bollywood" ,
    "Vlogger" ,
    "Vehicles" ,
    "Facebook" ,
    "Freelancer" ,
    "Facebook Page" ,
    "Designer" ,
    "Developer" ,
    "Web Designer" ,
    "Web Developer" ,
    "Divisor.in" ,
    "Login Form in HTML & CSS" ,
    "How to learn HTML & CSS" ,
    "How to learn Javascript" ,
    "How to became Freelancer" ,
    "How to became Web Designer" ,
    "How to start Gaming Channel" ,
    "How to start YouTube Channel" ,
    "What does HTML stands for?" ,
    "What does CSS stands for?" ,
 ];